multitenancy.tenants.tenant1.write.url=jdbc:h2:mem:tenant1;DB_CLOSE_DELAY=-1;MODE=LEGACY
multitenancy.tenants.tenant1.write.username=sa
multitenancy.tenants.tenant1.write.password=
multitenancy.tenants.tenant1.write.driver-class-name=org.h2.Driver
multitenancy.tenants.tenant1.read.url=jdbc:h2:mem:tenant1;DB_CLOSE_DELAY=-1;MODE=LEGACY
multitenancy.tenants.tenant1.read.username=sa
multitenancy.tenants.tenant1.read.password=
multitenancy.tenants.tenant1.read.driver-class-name=org.h2.Driver

multitenancy.tenants.tenant2.write.url=jdbc:h2:mem:tenant2;DB_CLOSE_DELAY=-1;MODE=LEGACY
multitenancy.tenants.tenant2.write.username=sa
multitenancy.tenants.tenant2.write.password=
multitenancy.tenants.tenant2.write.driver-class-name=org.h2.Driver
multitenancy.tenants.tenant2.read.url=jdbc:h2:mem:tenant2;DB_CLOSE_DELAY=-1;MODE=LEGACY
multitenancy.tenants.tenant2.read.username=sa
multitenancy.tenants.tenant2.read.password=
multitenancy.tenants.tenant2.read.driver-class-name=org.h2.Driver
